apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-n8nv
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-n8nv
    app.kubernetes.io/part-of: ci10t-777-0007-app
  name: devfile-sample-n8nv
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-n8nv
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-n8nv
    spec:
      containers:
      - image: quay.io/pmacik-testing/ci10t-777-0007-tenant/ci10t-777-0007-app/devfile-sample-n8nv@sha256:cf930294d3e59d337e1b2d4dd39eb71e012d961a2b3d049ff858110cc31a2aa7
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
